### ISSUE TITLE
cannot find package "g ithub.com/issue9/term/colors

### ISSUE THREAD

**Issue by jamesding** [issue9/logs#6]
github.com\issue9\logs\writers\console.go:10:2: cannot find package "github.com/issue9/term/colors"
你这个term/colors是哪来的

**Comment by caixw** [comment]
github.com/issue9/term/colors 是跨平台的控制台输出包。如果没有启用 GO111MODULE 的话，可能需要手动下载到 GOPATH，地址在 https://github.com/issue9/term
